#!/bin/sh
set -eu

destination=
url=
accept=
while test "$#" -gt 0
do
  case "$1" in
    --header)
      accept=$2
      shift 2
      ;;
    --output)
      destination=$2
      shift 2
      ;;
    http://*|https://*)
      url=$1
      shift
      ;;
    *) shift ;;
  esac
done
test -n "$destination"
case "$url" in
  *releases/download/v1.8.0/tla2tools.jar)
    test -z "$accept"
    source_file=$FLYOLOGY_TLA_TEST_JAR
    ;;
  *releases/assets/*)
    printf '%s\n' "deleted fixture asset: $url" >&2
    exit 22
    ;;
  *tlapm-*.tar.gz) source_file=$FLYOLOGY_TLA_TEST_TLAPM_ARCHIVE ;;
  *api.adoptium.net*) source_file=$FLYOLOGY_TLA_TEST_JAVA_ARCHIVE ;;
  *) printf '%s\n' "unexpected fixture URL: $url" >&2; exit 1 ;;
esac
cp "$source_file" "$destination"
