#!/bin/sh
set -eu

destination=
url=
while test "$#" -gt 0
do
  case "$1" in
    --output)
      destination=$2
      shift 2
      ;;
    http://*|https://*)
      url=$1
      shift
      ;;
    *) shift ;;
  esac
done
test -n "$destination"
case "$url" in
  *tla2tools.jar) source_file=$FLYOLOGY_TLA_TEST_JAR ;;
  *tlapm-*.tar.gz) source_file=$FLYOLOGY_TLA_TEST_TLAPM_ARCHIVE ;;
  *api.adoptium.net*) source_file=$FLYOLOGY_TLA_TEST_JAVA_ARCHIVE ;;
  *) printf '%s\n' "unexpected fixture URL: $url" >&2; exit 1 ;;
esac
cp "$source_file" "$destination"
