#!/bin/sh
set -eu

for final_argument do :; done
module_file=${final_argument##*/}
module_name=${module_file%.tla}

printf '%s\n' '<?xml version="1.0" encoding="UTF-8"?>'
printf '%s\n' '<modules>'
printf '  <RootModule>%s</RootModule>\n' "$module_name"
printf '%s\n' '  <context>'
if test "$module_name" = IdentityRoot
then
  printf '%s\n' '    <entry><ModuleNode><uniquename>IdentityHelper</uniquename></ModuleNode></entry>'
fi
printf '    <entry><ModuleNode><uniquename>%s</uniquename></ModuleNode></entry>\n' "$module_name"
printf '%s\n' '  </context>'
printf '%s\n' '</modules>'
